language: node_js
services: mongodb
sudo: required
matrix:
  fast_finish: true
  include:
    - name: Node.js 10
      node_js: 10
      env: RUN="yarn test"
    - name: Node.js 12
      node_js: 12
      env: RUN="yarn test"
    - name: Node.js 14 & lint
      node_js: 14
      env: RUN="yarn test && yarn lint"
addons:
  apt:
    sources:
      # gcc 4.8+ requires ubuntu-toolchain-r-test
      - ubuntu-toolchain-r-test
      - mongodb-upstart
      - mongodb-3.4-precise
    packages:
      # NodeJS v4+ requires gcc 4.8+
      - g++-4.9
      - gcc-4.9
      - mongodb-org-server
      - mongodb-org-shell
env:
  global:
    # NodeJS v4+ requires gcc 4.8+
    - CXX=g++-4.9 CC=gcc-4.9
    - TRAVIS=true
script: '$RUN'
before_script:
  - mongo --version
  - mongod --version
after_script: make test-coveralls
